Algoritmo "Exercicio 5"
// Disciplina   : CTP
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 21/03/2021
Var
// Seção de Declarações das variáveis 
celsius, fahrenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em graus Célsius: ")
leia(celsius)

fahrenheit:=(celsius*1.8)+32

escreva("Temperatura em Fahrenheit: ", fahrenheit)

Fimalgoritmo