Algoritmo "Exercicio 6"
// Disciplina   : CTP
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 21/03/2021
Var
// Seção de Declarações das variáveis 
altura, raio, volume:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a altura: ")
leia(altura)

escreval("Digite o valor do raio: ")
leia(raio)

volume:= 3.14*(raio*raio)*altura

escreva("Volume cúbico da lata: ",volume)
Fimalgoritmo