Algoritmo "Exercicio 3"
// Disciplina   : CTP
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 21/03/2021
Var
// Seção de Declarações das variáveis 
reais, cotacao, conversao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a cotação do dólar: ")
leia(cotacao)

escreval("Digite o valor em reais: ")
leia(reais)

conversao:=reais/cotacao

escreval("Valor em reais convertido para dólar: ", conversao)

Fimalgoritmo