Algoritmo "Exercicio 1"
// Disciplina   : CTP
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Data atual  : 21/03/2021
Var
// Seção de Declarações das variáveis 
numero_1, numero_2, numero_3, soma, quadrado :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite três números inteiros")
leia(numero_1, numero_2, numero_3)

soma:=numero_1+numero_2+numero_3
quadrado:=soma*soma

escreva("O quadrado da soma é ",quadrado)

Fimalgoritmo